
interface URIScheme {
  hasAuthority: boolean
}

export const schemes: { [scheme: string]: URIScheme } = {
  'http': { hasAuthority: true },
  'https': { hasAuthority: true },
  'file': { hasAuthority: false },
  'mailto': { hasAuthority: false },
  'tel': { hasAuthority: false },
  'data': { hasAuthority: false },
  'urn': { hasAuthority: false },
  'ftp': { hasAuthority: true },
  'sftp': { hasAuthority: true },
  'ssh': { hasAuthority: true },
  'git': { hasAuthority: true },
  'svn': { hasAuthority: true },
  'ws': { hasAuthority: true },
  'wss': { hasAuthority: true },
  'gopher': { hasAuthority: true },
  'ldap': { hasAuthority: true },
  'ldaps': { hasAuthority: true },
  'smtp': { hasAuthority: true },
  'imap': { hasAuthority: true },
  'pop': { hasAuthority: true },
  'rtsp': { hasAuthority: true },
  'rtmp': { hasAuthority: true },
  'rtmpt': { hasAuthority: true },
  'mms': { hasAuthority: true },
  'mmst': { hasAuthority: true },
  'mmsu': { hasAuthority: true },
  'mmsh': { hasAuthority: true },
  'rtp': { hasAuthority: true },
  'rtspu': { hasAuthority: true },
  'smb': { hasAuthority: true },
  'nfs': { hasAuthority: true },
  'dav': { hasAuthority: true },
  'news': { hasAuthority: true },
  'telnet': { hasAuthority: true },
  'sip': { hasAuthority: true },
  'sips': { hasAuthority: true },
  'xmpp': { hasAuthority: true },
  'irc': { hasAuthority: true },
  'ircs': { hasAuthority: true },
  'nntp': { hasAuthority: true },
  'rsync': { hasAuthority: true },
  'webcal': { hasAuthority: true },
  'webdav': { hasAuthority: true },
  'webdavs': { hasAuthority: true },
  'dict': { hasAuthority: true }
}